### ISSUE TITLE
haproxy-certbot keeps restarting endlessly

### ISSUE THREAD

**Issue by Geek-MD** [lemariva/haproxy-certbot#2]
Sorry to bother you, but haproxy-certbot keeps restarting endlessly. I've created the container using docker-compose file and env variables.

This is the result of "docker ps" command

```
c1435e93b3bc   lemariva/haproxy-certbot:1.1.2-SNAPSHOT        "/usr/bin/entry.sh /…"   27 minutes ago   Restarting (1) 3 seconds ago             haproxy-certbot
```

My "docker-compose.yaml" file is this

```
version: "3.8"
services:
  haproxy:
    restart: unless-stopped
    container_name: ${LOAD_BALANCER_NAME}
    image: ${DOCKER_REPO}/haproxy-certbot:${VERSION}
    volumes:
     - ./haproxy/config:/config
     - ./haproxy/letsencrypt:/etc/letsencrypt
     - ./haproxy/certs.d:/usr/local/etc/haproxy/certs.d
    ports:
     - "80:80"
     - "443:443"
     - "9999:9999"
    cap_add:
     - NET_ADMIN
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      FORCE_HTTPS_REDIRECT: "true"
      SERVICE_IP: 192.168.4.50
      SERVICE_PORT: 8123
```

And to create the container I use

```
docker-compose --env-file ../docker.env up -d
```

Please help. Thanks in advance.
